version: "3.9"
services:
  server:
    build: server/.
    volumes:
      - type: bind
        source: ./server/config/
        target: /root/.config/
      - type: bind
        source: ./server/database_folder/
        target: /database_folder/
    ports:
      - 5000:5000
    networks:
      - local
  client:
    build: client/.
    volumes:
      - type: bind
        source: ./client/config/
        target: /root/.config/
      - type: bind
        source: ./client/database_folder/
        target: /database_folder/
    networks:
      - local

networks:
  local:
    driver: bridge
